.TH "dct" 3 "Tue Nov 20 2018" "Version 1.0" "KPM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dct
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBdctgrid\fP"
.br
.ti -1c
.RI "subroutine, public \fBdctnaive\fP"
.br
.ti -1c
.RI "subroutine, public \fBdctdct\fP"
.br
.ti -1c
.RI "subroutine, public \fBdctfree\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real(dp), dimension(:), allocatable, public \fBen\fP"
.br
.ti -1c
.RI "real(dp), dimension(:,:), allocatable, public \fBgammak\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, public dct::dctdct ()"

.SS "subroutine, public dct::dctfree ()"

.SS "subroutine, public dct::dctgrid ()"

.SS "subroutine, public dct::dctnaive ()"

.SH "Variable Documentation"
.PP 
.SS "real(dp), dimension (:), allocatable, public dct::en"

.SS "real(dp), dimension (:,:), allocatable, public dct::gammak"

.SH "Author"
.PP 
Generated automatically by Doxygen for KPM from the source code\&.
