.TH "init" 3 "Tue Nov 20 2018" "Version 1.0" "KPM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
init
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBinitialize\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real(dp), public \fBtime_begin\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, public init::initialize ()"

.SH "Variable Documentation"
.PP 
.SS "real(dp), public init::time_begin"

.SH "Author"
.PP 
Generated automatically by Doxygen for KPM from the source code\&.
