.TH "kernel" 3 "Tue Nov 20 2018" "Version 1.0" "KPM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kernel
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBkercalc\fP"
.br
.ti -1c
.RI "subroutine, public \fBkerfree\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real(dp), dimension(:), allocatable, public \fBker\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, public kernel::kercalc ()"

.SS "subroutine, public kernel::kerfree ()"

.SH "Variable Documentation"
.PP 
.SS "real(dp), dimension (:), allocatable, public kernel::ker"

.SH "Author"
.PP 
Generated automatically by Doxygen for KPM from the source code\&.
