.TH "lattice" 3 "Tue Nov 20 2018" "Version 1.0" "KPM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lattice
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "integer function, public \fBlattsite\fP (ix, iy)"
.br
.ti -1c
.RI "subroutine, public \fBlattneighbors\fP (ix, iy, isiten)"
.br
.ti -1c
.RI "subroutine, public \fBlattdistrib\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, public \fBnlsite\fP"
.br
.ti -1c
.RI "integer, public \fBsitestart\fP"
.br
.ti -1c
.RI "integer, public \fBsiteend\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, public lattice::lattdistrib ()"

.SS "subroutine, public lattice::lattneighbors (integer, intent(in) ix, integer, intent(in) iy, integer, dimension(2), intent(out) isiten)"

.SS "integer function, public lattice::lattsite (integer, intent(in) ix, integer, intent(in) iy)"

.SH "Variable Documentation"
.PP 
.SS "integer, public lattice::nlsite"

.SS "integer, public lattice::siteend"

.SS "integer, public lattice::sitestart"

.SH "Author"
.PP 
Generated automatically by Doxygen for KPM from the source code\&.
