.TH "/home/pedro/local/src/kpm/src/lattice.F90" 3 "Tue Nov 20 2018" "Version 1.0" "KPM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/pedro/local/src/kpm/src/lattice.F90
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBlattice\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "integer function, public \fBlattice::lattsite\fP (ix, iy)"
.br
.ti -1c
.RI "subroutine, public \fBlattice::lattneighbors\fP (ix, iy, isiten)"
.br
.ti -1c
.RI "subroutine, public \fBlattice::lattdistrib\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, public \fBlattice::nlsite\fP"
.br
.ti -1c
.RI "integer, public \fBlattice::sitestart\fP"
.br
.ti -1c
.RI "integer, public \fBlattice::siteend\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for KPM from the source code\&.
