.TH "moment" 3 "Tue Nov 20 2018" "Version 1.0" "KPM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moment
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBminit\fP"
.br
.ti -1c
.RI "subroutine, public \fBmcalc\fP"
.br
.ti -1c
.RI "subroutine, public \fBmfree\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real(dp), dimension(:,:), allocatable, public \fBlmu\fP"
.br
.ti -1c
.RI "real(dp), dimension(:,:), allocatable, public \fBmuh\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, public moment::mcalc ()"

.SS "subroutine, public moment::mfree ()"

.SS "subroutine, public moment::minit ()"

.SH "Variable Documentation"
.PP 
.SS "real(dp), dimension (:,:), allocatable, public moment::lmu"

.SS "real(dp), dimension (:,:), allocatable, public moment::muh"

.SH "Author"
.PP 
Generated automatically by Doxygen for KPM from the source code\&.
