.TH "options" 3 "Tue Nov 20 2018" "Version 1.0" "KPM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
options
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBoptread\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "logical \fBmemory\fP"
.br
.ti -1c
.RI "integer \fBlattorder\fP"
.br
.ti -1c
.RI "integer \fBpoldegree\fP"
.br
.ti -1c
.RI "integer \fBnsteps\fP"
.br
.ti -1c
.RI "integer \fBdstart\fP"
.br
.ti -1c
.RI "integer \fBngrid\fP"
.br
.ti -1c
.RI "integer \fBnumthreads\fP"
.br
.ti -1c
.RI "integer, parameter \fBlabel_len\fP = 60"
.br
.ti -1c
.RI "real(dp) \fBenergymin\fP"
.br
.ti -1c
.RI "real(dp) \fBenergymax\fP"
.br
.ti -1c
.RI "real(dp) \fBdelta\fP"
.br
.ti -1c
.RI "real(dp) \fBthop\fP"
.br
.ti -1c
.RI "real(dp) \fBdw\fP"
.br
.ti -1c
.RI "real(dp) \fBlresol\fP"
.br
.ti -1c
.RI "character(len=\fBlabel_len\fP) \fBslabel\fP"
.br
.ti -1c
.RI "character(len=8) \fBkerlabel\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine options::optread ()"

.SH "Variable Documentation"
.PP 
.SS "real(dp) options::delta"

.SS "integer options::dstart"

.SS "real(dp) options::dw"

.SS "real(dp) options::energymax"

.SS "real(dp) options::energymin"

.SS "character(len=8) options::kerlabel"

.SS "integer, parameter options::label_len = 60"

.SS "integer options::lattorder"

.SS "real(dp) options::lresol"

.SS "logical options::memory"

.SS "integer options::ngrid"

.SS "integer options::nsteps"

.SS "integer options::numthreads"

.SS "integer options::poldegree"

.SS "character(len=\fBlabel_len\fP) options::slabel"

.SS "real(dp) options::thop"

.SH "Author"
.PP 
Generated automatically by Doxygen for KPM from the source code\&.
