.TH "precision" 3 "Tue Nov 20 2018" "Version 1.0" "KPM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
precision
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, parameter \fBsp\fP = selected_real_kind(6, 30)"
.br
.ti -1c
.RI "integer, parameter \fBdp\fP = selected_real_kind(14, 100)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "integer, parameter precision::dp = selected_real_kind(14, 100)"

.SS "integer, parameter precision::sp = selected_real_kind(6, 30)"

.SH "Author"
.PP 
Generated automatically by Doxygen for KPM from the source code\&.
