.TH "/home/pedro/local/src/kpm/src/hadt.F90" 3 "Tue Nov 20 2018" "Version 1.0" "KPM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/pedro/local/src/kpm/src/hadt.F90
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBhadt\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBhadt::adtcreate\fP (nH)"
.br
.ti -1c
.RI "subroutine, public \fBhadt::adtinsert\fP (site, key)"
.br
.ti -1c
.RI "subroutine, public \fBhadt::adtfree\fP (nH)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "type(idxhopptr), dimension(:), allocatable, public \fBhadt::idxh\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for KPM from the source code\&.
