.TH "hadt" 3 "Tue Nov 20 2018" "Version 1.0" "KPM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hadt
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBadtcreate\fP (nH)"
.br
.ti -1c
.RI "subroutine, public \fBadtinsert\fP (site, key)"
.br
.ti -1c
.RI "subroutine, public \fBadtfree\fP (nH)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "type(idxhopptr), dimension(:), allocatable, public \fBidxh\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, public hadt::adtcreate (integer, intent(in) nH)"

.SS "subroutine, public hadt::adtfree (integer, intent(in) nH)"

.SS "subroutine, public hadt::adtinsert (integer, intent(in) site, integer, intent(in) key)"

.SH "Variable Documentation"
.PP 
.SS "type(idxhopptr), dimension (:), allocatable, public hadt::idxh"

.SH "Author"
.PP 
Generated automatically by Doxygen for KPM from the source code\&.
