.TH "/home/pedro/local/src/kpm/src/hsparse.F90" 3 "Tue Nov 20 2018" "Version 1.0" "KPM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/pedro/local/src/kpm/src/hsparse.F90
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBhsparse\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBhsparse::hrescale\fP"
.br
.ti -1c
.RI "subroutine, public \fBhsparse::hfree\fP"
.br
.ti -1c
.RI "subroutine, public \fBhsparse::hbcast\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, public \fBhsparse::nh\fP"
.br
.ti -1c
.RI "integer, public \fBhsparse::nelem\fP"
.br
.ti -1c
.RI "integer, dimension(:), allocatable, public \fBhsparse::hcol\fP"
.br
.ti -1c
.RI "integer, dimension(:), allocatable, public \fBhsparse::hrow\fP"
.br
.ti -1c
.RI "real(dp), dimension(:), allocatable, public \fBhsparse::hval\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for KPM from the source code\&.
