.TH "/home/pedro/local/src/kpm/src/kernel.F90" 3 "Tue Nov 20 2018" "Version 1.0" "KPM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/pedro/local/src/kpm/src/kernel.F90
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBkernel\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBkernel::kercalc\fP"
.br
.ti -1c
.RI "subroutine, public \fBkernel::kerfree\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real(dp), dimension(:), allocatable, public \fBkernel::ker\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for KPM from the source code\&.
