.TH "/home/pedro/local/src/kpm/src/options.F90" 3 "Tue Nov 20 2018" "Version 1.0" "KPM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/pedro/local/src/kpm/src/options.F90
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBoptions\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBoptions::optread\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "logical \fBoptions::memory\fP"
.br
.ti -1c
.RI "integer \fBoptions::lattorder\fP"
.br
.ti -1c
.RI "integer \fBoptions::poldegree\fP"
.br
.ti -1c
.RI "integer \fBoptions::nsteps\fP"
.br
.ti -1c
.RI "integer \fBoptions::dstart\fP"
.br
.ti -1c
.RI "integer \fBoptions::ngrid\fP"
.br
.ti -1c
.RI "integer \fBoptions::numthreads\fP"
.br
.ti -1c
.RI "integer, parameter \fBoptions::label_len\fP = 60"
.br
.ti -1c
.RI "real(dp) \fBoptions::energymin\fP"
.br
.ti -1c
.RI "real(dp) \fBoptions::energymax\fP"
.br
.ti -1c
.RI "real(dp) \fBoptions::delta\fP"
.br
.ti -1c
.RI "real(dp) \fBoptions::thop\fP"
.br
.ti -1c
.RI "real(dp) \fBoptions::dw\fP"
.br
.ti -1c
.RI "real(dp) \fBoptions::lresol\fP"
.br
.ti -1c
.RI "character(len=label_len) \fBoptions::slabel\fP"
.br
.ti -1c
.RI "character(len=8) \fBoptions::kerlabel\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for KPM from the source code\&.
