.TH "parallel" 3 "Tue Nov 20 2018" "Version 1.0" "KPM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
parallel
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, save \fBnode\fP = 0"
.br
.ti -1c
.RI "integer, save \fBnodes\fP = 1"
.br
.ti -1c
.RI "logical, save \fBionode\fP = \&.false\&."
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "logical, save parallel::ionode = \&.false\&."

.SS "integer, save parallel::node = 0"

.SS "integer, save parallel::nodes = 1"

.SH "Author"
.PP 
Generated automatically by Doxygen for KPM from the source code\&.
