.TH "/home/pedro/local/src/kpm/src/parallel.F90" 3 "Tue Nov 20 2018" "Version 1.0" "KPM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/pedro/local/src/kpm/src/parallel.F90
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBparallel\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, save \fBparallel::node\fP = 0"
.br
.ti -1c
.RI "integer, save \fBparallel::nodes\fP = 1"
.br
.ti -1c
.RI "logical, save \fBparallel::ionode\fP = \&.false\&."
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for KPM from the source code\&.
