.TH "string" 3 "Tue Nov 20 2018" "Version 1.0" "KPM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
string
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBstrconcat\fP (str1, str2, str3)"
.br
.ti -1c
.RI "subroutine, public \fBstrpaste\fP (str1, str2, str3)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, public string::strconcat (character*(*), intent(in) str1, character*(*), intent(in) str2, character*(*), intent(out) str3)"

.SS "subroutine, public string::strpaste (character*(*), intent(in) str1, character*(*), intent(in) str2, character*(*), intent(out) str3)"

.SH "Author"
.PP 
Generated automatically by Doxygen for KPM from the source code\&.
